import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const url = process.env.TEST_URL || 'http://127.0.0.1:3100';
const duration = 16.1;
const browser = await chromium.launch({ channel:'chrome', headless:true });
await mkdir('test-results', { recursive:true });
const results = [];
try {
 const page = await browser.newPage({ viewport:{ width:1440,height:900 } });
 const errors = [];
 page.on('pageerror', error => errors.push(error.message));
 await page.goto(url); await page.waitForSelector('.is-cinematic'); await page.waitForTimeout(500);
 assert.match(await page.title(), /FUXION/);
 await page.screenshot({ path:'test-results/desktop-intro.png' });
 const seek = async (time, mobile=false) => {
   await page.evaluate(({time,mobile,duration}) => window.scrollTo(0,window.innerHeight*(mobile?13:16)*time/duration),{time,mobile,duration});
   await page.waitForTimeout(1100);
 };
 for (const [slug,time] of [['thermo-t',2.35],['nocarb-t',6.6],['beauty-in',11.5]]) {
   await seek(time);
   assert.equal(await page.locator(`#${slug}`).getAttribute('aria-hidden'),'false');
   await page.screenshot({path:`test-results/desktop-${slug}.png`});
   await seek(time+(slug==='thermo-t'?1.1:1.5));
   const opacity = await page.locator(`#${slug} .glass-assembly`).evaluate(el=>+getComputedStyle(el).opacity);
   assert.ok(opacity>0.9,`${slug} glass must reveal`);
   await page.screenshot({path:`test-results/desktop-${slug}-pour.png`});
   await seek(time+(slug==='thermo-t'?3.3:2));
   assert.ok(await page.locator(`#${slug}`).evaluate(el=>+getComputedStyle(el).opacity)>.9,`${slug} scene must remain visible through its editorial beat`);
 }
 results.push('Desktop: all three product reveals and preparations');
 await seek(14.6);
 assert.ok(await page.evaluate(()=>scrollY)>0);
 await page.screenshot({path:'test-results/desktop-final.png'});
 await page.getByRole('button',{name:'Volver a vivir la experiencia'}).click();
 await page.waitForTimeout(2200);
 assert.ok(await page.evaluate(()=>scrollY)<10);
 results.push('Final CTA replays to the beginning');
 await page.getByRole('button',{name:'NOCARB-T',exact:true}).click(); await page.waitForTimeout(2000);
 assert.ok(await page.evaluate(()=>scrollY)>0);
 await seek(2.35); assert.equal(await page.locator('#thermo-t').getAttribute('aria-hidden'),'false');
 assert.equal(await page.locator('#thermo-t .thermo-procedural').evaluate(el=>getComputedStyle(el).display),'none');
 results.push('Chapter navigation and reverse scrolling');
 await page.getByRole('button',{name:'Ver sin animación'}).click();
 await page.waitForTimeout(500);
 assert.equal(await page.locator('.pin-spacer').count(),0);
 assert.equal(await page.locator('.scene[inert]').count(),0);
 await page.getByRole('button',{name:'BEAUTY-IN',exact:true}).click();
 assert.ok(await page.locator('#beauty-in').evaluate(el=>Math.abs(el.getBoundingClientRect().top)<100));
 results.push('Static view cleans pinning and supports chapter navigation');
 await page.getByRole('button',{name:'Vista sin animación'}).click();
 await page.waitForSelector('.is-cinematic');
 assert.equal(await page.locator('.pin-spacer').count(),1);
 results.push('Re-entering cinema creates exactly one pin');
 await page.setViewportSize({width:390,height:844});
 await page.waitForTimeout(700);
 assert.equal(await page.locator('.pin-spacer').count(),1);
 results.push('Desktop-to-mobile resize preserves a single timeline');
 await page.reload(); await page.waitForSelector('.is-cinematic');
 await seek(0.6,true); await page.screenshot({path:'test-results/mobile-intro.png'});
 await seek(3.7,true); await page.screenshot({path:'test-results/mobile-pour.png'});
 await seek(4.3,true); await page.screenshot({path:'test-results/mobile-product-details.png'});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await seek(13.8,true); await page.screenshot({path:'test-results/mobile-final.png'});
 await page.setViewportSize({width:320,height:568}); await page.waitForTimeout(500);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 results.push('Mobile 390px: intro, preparation, final, no horizontal overflow');
 await page.emulateMedia({reducedMotion:'reduce'}); await page.reload(); await page.waitForTimeout(800);
 assert.equal(await page.locator('.pin-spacer').count(),0);
 assert.equal(await page.locator('.scene[inert]').count(),0);
 for(const slug of ['thermo-t','nocarb-t','beauty-in']) assert.ok(await page.locator(`#${slug}`).isVisible());
 await page.screenshot({path:'test-results/reduced-motion.png',fullPage:true});
 results.push('Reduced motion: all products in natural document flow');
 const noJS = await browser.newPage({javaScriptEnabled:false,viewport:{width:1280,height:800}});
 await noJS.goto(url);
 assert.ok(await noJS.getByRole('heading',{name:'BEAUTY-IN',exact:true}).isVisible());
 results.push('Without JavaScript: product content remains readable');
 assert.deepEqual(errors,[]);
 results.push('No uncaught browser errors');
 console.log(JSON.stringify({pass:true,results},null,2));
 await writeFile('test-results/report.json',JSON.stringify({pass:true,results},null,2));
} finally { await browser.close(); }
